### ISSUE TITLE
Failing to run simple/main.go from _examples

### ISSUE THREAD

**Issue by jpoz** [aarzilli/nucular#51]
Trying to run `main.go` in `_examples/simple` getting a `SIGILL: illegal instruction`

```
simple $ pwd                                                                                                                                                                                               master1 ↵
/Users/jpoz/go/src/github.com/aarzilli/nucular/_examples/simple
simple $ go run main.go                                                                                                                                                                                       master
SIGILL: illegal instruction
PC=0x7fff2c0b98a1 m=4 sigcode=1
signal arrived during cgo execution

goroutine 26 [syscall, locked to thread]:
runtime.cgocall(0x4117d90, 0xc000048f10, 0x41164d6)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000048ee0 sp=0xc000048ea8 pc=0x4005a2b
golang.org/x/exp/shiny/driver/gldriver._Cfunc_makeCurrentContext(0x739ab00)
        _cgo_gotypes.go:298 +0x41 fp=0xc000048f10 sp=0xc000048ee0 pc=0x40fca11
golang.org/x/exp/shiny/driver/gldriver.drawLoop(0xc0001c4000, 0x1)
        /Users/jpoz/go/pkg/mod/golang.org/x/exp@v0.0.0-20191024150812-c286b889502e/shiny/driver/gldriver/cocoa.go:147 +0x60 fp=0xc000048fd0 sp=0xc000048f10 pc=0x40fdac0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000048fd8 sp=0xc000048fd0 pc=0x4059e51
created by golang.org/x/exp/shiny/driver/gldriver.preparedOpenGL
        /Users/jpoz/go/pkg/mod/golang.org/x/exp@v0.0.0-20191024150812-c286b889502e/shiny/driver/gldriver/cocoa.go:92 +0xe4

goroutine 1 [chan receive, locked to thread]:
golang.org/x/exp/shiny/driver/gldriver.drawgl(0x7363580)
        /Users/jpoz/go/pkg/mod/golang.org/x/exp@v0.0.0-20191024150812-c286b889502e/shiny/driver/gldriver/cocoa.go:134 +0x15e
golang.org/x/exp/shiny/driver/gldriver._cgoexpwrap_db502a3a14da_drawgl(0x7363580)
        _cgo_gotypes.go:377 +0x2b
golang.org/x/exp/shiny/driver/gldriver._Cfunc_startDriver()
        _cgo_gotypes.go:311 +0x41
golang.org/x/exp/shiny/driver/gldriver.main(0xc00008e3f0, 0x400eff8, 0x10)
        /Users/jpoz/go/pkg/mod/golang.org/x/exp@v0.0.0-20191024150812-c286b889502e/shiny/driver/gldriver/cocoa.go:107 +0x4d
golang.org/x/exp/shiny/driver/gldriver.Main(0xc00008e3f0)
        /Users/jpoz/go/pkg/mod/golang.org/x/exp@v0.0.0-20191024150812-c286b889502e/shiny/driver/gldriver/gldriver.go:26 +0x2f
golang.org/x/exp/shiny/driver.main(...)
        /Users/jpoz/go/pkg/mod/golang.org/x/exp@v0.0.0-20191024150812-c286b889502e/shiny/driver/driver_darwin.go:15
golang.org/x/exp/shiny/driver.Main(...)
        /Users/jpoz/go/pkg/mod/golang.org/x/exp@v0.0.0-20191024150812-c286b889502e/shiny/driver/driver.go:24
github.com/aarzilli/nucular.(*masterWindow).Main(0xc0000c2000)
        /Users/jpoz/go/src/github.com/aarzilli/nucular/shiny.go:73 +0x58
main.main()
        /Users/jpoz/go/src/github.com/aarzilli/nucular/_examples/simple/main.go:15 +0xc2

goroutine 19 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000c21b0, 0xc0001c4000, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000c21ac)
        /usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/aarzilli/nucular.(*masterWindow).main(0xc0000c2000, 0x41a79e0, 0x42a9b60)
        /Users/jpoz/go/src/github.com/aarzilli/nucular/shiny.go:100 +0x2b0
golang.org/x/exp/shiny/driver/gldriver.driverStarted.func1()
        /Users/jpoz/go/pkg/mod/golang.org/x/exp@v0.0.0-20191024150812-c286b889502e/shiny/driver/gldriver/cocoa.go:114 +0x40
created by golang.org/x/exp/shiny/driver/gldriver.driverStarted
        /Users/jpoz/go/pkg/mod/golang.org/x/exp@v0.0.0-20191024150812-c286b889502e/shiny/driver/gldriver/cocoa.go:113 +0x35

goroutine 6 [chan receive]:
golang.org/x/mobile/gl.(*context).enqueue(0xc0001c8000, 0x57, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jpoz/go/pkg/mod/golang.org/x/mobile@v0.0.0-20190719004257-d2bd2a29d028/gl/work.go:111 +0xd3
golang.org/x/mobile/gl.(*context).IsProgram(0xc0001c8000, 0xcfc00, 0x8)
        /Users/jpoz/go/pkg/mod/golang.org/x/mobile@v0.0.0-20190719004257-d2bd2a29d028/gl/gl.go:1045 +0xcb
golang.org/x/exp/shiny/driver/gldriver.(*screenImpl).NewTexture(0x42a9b60, 0x500, 0x3c0, 0x0, 0x0, 0x0, 0x0)
        /Users/jpoz/go/pkg/mod/golang.org/x/exp@v0.0.0-20191024150812-c286b889502e/shiny/driver/gldriver/screen.go:78 +0x1a0
golang.org/x/exp/shiny/driver/gldriver.(*windowImpl).Upload(0xc0001c4000, 0x0, 0x0, 0x41a8060, 0xc0006b4000, 0x0, 0x0, 0x500, 0x3c0)
        /Users/jpoz/go/pkg/mod/golang.org/x/exp@v0.0.0-20191024150812-c286b889502e/shiny/driver/gldriver/window.go:126 +0x126
github.com/aarzilli/nucular.(*masterWindow).updateLocked(0xc0000c2000)
        /Users/jpoz/go/src/github.com/aarzilli/nucular/shiny.go:279 +0x274
github.com/aarzilli/nucular.(*masterWindow).updater.func1(0xc0000c2000, 0xc000048fc7)
        /Users/jpoz/go/src/github.com/aarzilli/nucular/shiny.go:226 +0x136
github.com/aarzilli/nucular.(*masterWindow).updater(0xc0000c2000)
        /Users/jpoz/go/src/github.com/aarzilli/nucular/shiny.go:238 +0x3c
created by github.com/aarzilli/nucular.(*masterWindow).main
        /Users/jpoz/go/src/github.com/aarzilli/nucular/shiny.go:96 +0x1c8

rax    0x0
rbx    0xc000048f10
rcx    0x0
rdx    0x0
rdi    0x0
rsi    0x1f08000c
rbp    0x70000e059ef0
rsp    0x70000e059eb0
r8     0x0
r9     0x0
r10    0x0
r11    0x0
r12    0x739ab00
r13    0x0
r14    0x40
r15    0xffffffffffffffff
rip    0x7fff2c0b98a1
rflags 0x10202
cs     0x2b
fs     0x0
gs     0x0
exit status 2
```

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jpoz/Library/Caches/go-build"
GOENV="/Users/jpoz/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/jpoz/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/jpoz/go/src/github.com/aarzilli/nucular/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/6q/9ybmhmsd487f1m9f5d51g54w0000gp/T/go-build133797095=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by aarzilli** [comment]
It's a problem with shiny see https://github.com/golang/go/issues/35177
